/-
# Bailey campaign, Tier 2: Bailey pairs (the seed of the Bailey chain)

The mock theta conjectures (formalized in NO proof assistant — the world-first target) are proved by
Hickerson's method via **Bailey pairs**. A Bailey pair relative to `a = 1` is a pair of sequences `(αₙ, βₙ)`
over `ℤ⟦X⟧` (`q := X`) linked by the lower-triangular relation

  βₙ = Σ_{r≤n} αᵣ / ((q;q)_{n-r} · (q;q)_{n+r}).

The denominators `(q;q)_m = ∏_{k=1}^m (1 - qᵏ)` have constant term 1, hence are units, so the `1/(…)` are
genuine power series (`Ring.inverse`), exactly as for the mock theta functions themselves.

This file gives Tier 2's foundational objects: `(q;q)_m` with its invertibility, the `IsBaileyPair`
predicate, and the **seed (unit) Bailey pair** `α = δ_{·,0}`, `βₙ = 1/(q;q)ₙ²` — the base of the Bailey
chain, from which Rogers–Ramanujan- and mock-theta-type identities are generated by iterating Bailey's lemma
(Tier 2c, the genuine research wall ahead). No `sorry`.
-/
import Mathlib.RingTheory.PowerSeries.Inverse
import RamanujanTau.MockTheta5Bailey

namespace MockTheta5.Bailey
open PowerSeries

/-- `(q;q)_m = ∏_{k=1}^{m} (1 - qᵏ)`, the q-factorial. -/
noncomputable def qfac (m : ℕ) : PowerSeries ℤ := ∏ k ∈ Finset.range m, (1 - X ^ (k + 1))

@[simp] lemma qfac_zero : qfac 0 = 1 := by simp [qfac]

/-- Every factor `(1 - q^{k+1})` has constant term 1, so does the product `(q;q)_m`. -/
lemma constantCoeff_qfac (m : ℕ) : constantCoeff (qfac m) = 1 := by
  induction m with
  | zero => simp [qfac]
  | succ k ih =>
      rw [qfac, Finset.prod_range_succ, ← qfac, map_mul, ih, map_sub, map_one, map_pow,
          constantCoeff_X, zero_pow (Nat.succ_ne_zero k), sub_zero, mul_one]

/-- The q-factorial is a unit, so `1/(q;q)_m` is a genuine power series. -/
lemma isUnit_qfac (m : ℕ) : IsUnit (qfac m) := by
  rw [isUnit_iff_constantCoeff, constantCoeff_qfac]; exact isUnit_one

/-- A **Bailey pair relative to `a = 1`**: `β` is recovered from `α` by the lower-triangular sum
`βₙ = Σ_{r≤n} αᵣ / ((q;q)_{n-r}·(q;q)_{n+r})`. -/
def IsBaileyPair (α β : ℕ → PowerSeries ℤ) : Prop :=
  ∀ n, β n = ∑ r ∈ Finset.range (n + 1),
    α r * Ring.inverse (qfac (n - r)) * Ring.inverse (qfac (n + r))

/-- The **seed Bailey pair**: `αₙ = δ_{n,0}`. -/
noncomputable def seedAlpha (n : ℕ) : PowerSeries ℤ := if n = 0 then 1 else 0
/-- The **seed Bailey pair**: `βₙ = 1/(q;q)ₙ²`. -/
noncomputable def seedBeta (n : ℕ) : PowerSeries ℤ := Ring.inverse (qfac n) * Ring.inverse (qfac n)

/-- The seed pair `(δ_{·,0}, 1/(q;q)·²)` is a Bailey pair — the base of the Bailey chain. -/
theorem isBaileyPair_seed : IsBaileyPair seedAlpha seedBeta := by
  intro n
  rw [seedBeta, Finset.sum_eq_single_of_mem 0 (Finset.mem_range.mpr (Nat.succ_pos n))
        (fun r _ hr => by simp [seedAlpha, hr])]
  simp [seedAlpha]

end MockTheta5.Bailey
